version: '3'

services:
  app:
    build: ./blogOnline
    container_name: blog_app
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      SS_USER: juliMillen
      SS_PASSWORD: 12345
      DB_URL: jdbc:postgresql://db:5432/blogDB
      DB_USERNAME: postgres
      DB_PASSWORD: 42576661
      GITHUB_CLIENT_ID: Ov23litDKlk7R6jEDPop
      GITHUB_CLIENT_SECRET: 38ffae38b82cf733d5ff988358d15e4e79eb95d3
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    image: postgres:17
    container_name: blog_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: blogDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 42576661
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d blogDB"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s


