 spring.application.name=blogOnline

#Configuration Security

spring.security.user.name=${SS_USER}
spring.security.user.password=${SS_PASSWORD}

#Configuration BD

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


#Configuration OAUTH con GITHUB
spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}

#Configuration OAUTH con GOOGLE <--- sin implementar
#spring.security.oauth2.client.registration.google-client-id=${GOOGLE_CLIENT_ID}
#spring.security.oauth2.client.registration.google-client-secret=${GOOGLE_CLIENT_SECRET}